---
- name: Certificate manage example
  hosts: ipaserver
  become: false
  gather_facts: false
  module_defaults:
    ipacert:
      ipaadmin_password: SomeADMINpassword
      ipaapi_context: client

  tasks:
  - name: Release a certificate hold
    ipacert:
      ipaadmin_password: SomeADMINpassword
      serial_number: 12345
      state: released
